### ISSUE TITLE
log file permission

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_hri#6]
When I try to run 

``` bash
roslaunch ros_mary_tts ros_mary.launch
```

with my user, I get the following error:

MARY server 5.0 starting as a HTTP server...process[ros_mary_bridge-2]: started with pid [13962]
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /opt/strands/strands_catkin_ws/src/strands_hri/ros_mary_tts/marytts-5.0/log/server.log (Permission denied)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:212)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:136)
    at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
    at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
    at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
    at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
    at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
    at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:809)
    at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:735)
    at org.apache.log4j.PropertyConfigurator.parseCatsAndRenderers(PropertyConfigurator.java:639)
    at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:504)
    at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:428)
    at marytts.server.Mary.configureLogging(Mary.java:371)
    at marytts.server.Mary.startup(Mary.java:227)
    at marytts.server.Mary.startup(Mary.java:205)
    at marytts.server.Mary.main(Mary.java:508)

I can change the file permissions here and solve the problem (or run this as user strands), though I don't know if there should be a global solution where anyone can run this node without any extra permission change

**Comment by marc-hanheide** [comment]
should be fixed now (by not creating a log file in first place), if not please reopen
